<a href="https://colab.research.google.com/github/Shwetankjais/DAV_Lab/blob/main/4NI25CS193_Exp_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

print("Numpy version:", np.__version__)
print("Pandas version:", pd.__version__)

Numpy version: 2.0.2
Pandas version: 2.2.3


In [ ]:
marks=np.array([78,85,92,67,88])
print("Marks:", marks)
print("Type:",type(marks))

Marks: [78 85 92 67 88]
Type: <class 'numpy.ndarray'>


In [ ]:
print("Number of dimensions:", marks.ndim)
print("Shape:", marks.shape)
print("Number of elements:",marks.size)

Number of dimensions: 1
Shape: (5,)
Number of elements: 5


In [ ]:
marks=np.array([78,85,92,67,88])

print("Original:",marks)
print("Add 5:", marks+5)
print("Multiply by 2:",marks*2)
print("Divide by 2:",marks/2)
print("Square:",marks**2)

Original: [78 85 92 67 88]
Add 5: [83 90 97 72 93]
Multiply by 2: [156 170 184 134 176]
Divide by 2: [39.  42.5 46.  33.5 44. ]
Square: [6084 7225 8464 4489 7744]


In [ ]:
print("Sum:",marks.sum())
print("Mean:", marks.mean())
print("Maximum:",marks.max())
print("Minimum:",marks.min())

Sum: 410
Mean: 82.0
Maximum: 92
Minimum: 67


In [ ]:
print("First mark:",marks[0])
print("Second mark:", marks[1])
print("Third mark:",marks[-1])

First mark: 78
Second mark: 85
Third mark: 88


In [ ]:
print("Index 1 to 3:", marks[1:4])
print("First three:", marks[:3])
print("From index 2:",marks[2:])
print("Every second element:",marks[::2])

Index 1 to 3: [85 92 67]
First three: [78 85 92]
From index 2: [92 67 88]
Every second element: [78 92 88]


In [ ]:
student_marks = np.array([
    [78,85,92],
    [67,88,76],
    [90,95,89]
])
print(student_marks)
print("Shape:",student_marks.shape)

[[78 85 92]
 [67 88 76]
 [90 95 89]]
Shape: (3, 3)


In [ ]:
print("Mean of all values:",student_marks.mean())
print("Column wise Mean:", student_marks.mean(axis=0))
print("Row wise Mean:",student_marks.mean(axis=1))

Mean of all values: 84.44444444444444
Column wise Mean: [78.33333333 89.33333333 85.66666667]
Row wise Mean: [85.         77.         91.33333333]


In [ ]:
data={
    "Name": ["Anu","Rahul","Kiran","Priya"],
    "Branch": ["CSE","AIML","CSE","AIML"],
    "Marks": [85,91,76,88]
}
df = pd.DataFrame(data)
df

,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
print("Shape:",df.shape)
print("\n Columns:")
print(df.columns)

Shape: (4, 3)

 Columns:
Index(['Name', 'Branch', 'Marks'], dtype='object')


In [ ]:
df.head()

,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
df.tail()

,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Branch  4 non-null      object
 2   Marks   4 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [ ]:
df.describe()

,Marks
count,4.000000
mean,85.000000
std,6.480741
min,76.000000
25%,82.750000
50%,86.500000
75%,88.750000
max,91.000000


In [ ]:
print("Marks column:")
print(df["Marks"])
print("\nBrnch and Marks:")
print(df[["Branch","Marks"]])

Marks column:
0    85
1    91
2    76
3    88
Name: Marks, dtype: int64

Brnch and Marks:
  Branch  Marks
0    CSE     85
1   AIML     91
2    CSE     76
3   AIML     88


In [ ]:
print("First row:")
print(df.iloc[0])

print("\n Second row:")
print(df.iloc[1])

print("\n First three rows:")
print(df.iloc[0:3])

First row:
Name      Anu
Branch    CSE
Marks      85
Name: 0, dtype: object

 Second row:
Name      Rahul
Branch     AIML
Marks        91
Name: 1, dtype: object

 First three rows:
    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76


In [ ]:
print("First two rows and first two columns")
print(df.iloc[0:2,0:2])

First two rows and first two columns
    Name Branch
0    Anu    CSE
1  Rahul   AIML


In [ ]:
print("First three rows:")
display(df.iloc[0:3])
print("Rows 1 to 3, Name and Marks:")
display(df.iloc[1:4,0:3])

First three rows:


,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
2,Kiran,CSE,76


Rows 1 to 3, Name and Marks:


,Name,Branch,Marks
1,Rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
high_scorers = df[df["Marks"]>90]
high_scorers

,Name,Branch,Marks
1,Rahul,AIML,91


In [ ]:
print("Students from CSE:")
display(df[df["Branch"]=="CSE"])

print("Students scoring 85 or above:")
display(df[df["Marks"]>= 85])

Students from CSE:


,Name,Branch,Marks
0,Anu,CSE,85
2,Kiran,CSE,76


Students scoring 85 or above:


,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
3,Priya,AIML,88


In [ ]:
data = {
    "Name":["Shivansh","Bharti","Shwetank","Shaswat","SSK"],
    "Department":["CSE","ISE","CSE","AIML","ISE"],
    "Marks":[72,91,84,96,75],
    "Attendance":[82,93,88,75,85]
}
df=pd.DataFrame(data)
df

,Name,Department,Marks,Attendance
0,Shivansh,CSE,72,82
1,Bharti,ISE,91,93
2,Shwetank,CSE,84,88
3,Shaswat,AIML,96,75
4,SSK,ISE,75,85


In [ ]:
df[["Name", "Marks"]]

,Name,Marks
0,Shivansh,72
1,Bharti,91
2,Shwetank,84
3,Shaswat,96
4,SSK,75


In [ ]:
more_80 = df[df["Marks"]>80]
more_80

,Name,Department,Marks,Attendance
1,Bharti,ISE,91,93
2,Shwetank,CSE,84,88
3,Shaswat,AIML,96,75


In [ ]:
more_85 = df[df["Attendance"]>80]
more_85

,Name,Department,Marks,Attendance
0,Shivansh,CSE,72,82
1,Bharti,ISE,91,93
2,Shwetank,CSE,84,88
4,SSK,ISE,75,85


In [ ]:
print("First three rows:")
display(df.iloc[0:3])

First three rows:


,Name,Department,Marks,Attendance
0,Shivansh,CSE,72,82
1,Bharti,ISE,91,93
2,Shwetank,CSE,84,88


In [ ]:
average_marks = df["Marks"].mean()
print("Average Marks:", average_marks)

Average Marks: 83.6


In [ ]:
maximum_marks = df["Marks"].max()
print("Maximum Marks:", maximum_marks)

Maximum Marks: 96


In [ ]:
cse_students = df[df["Department"] == "CSE"]
print(cse_students)

       Name Department  Marks  Attendance
0  Shivansh        CSE     72          82
2  Shwetank        CSE     84          88


In [ ]:
df[(df["Marks"] > 80) & (df["Attendance"] > 85)]

,Name,Department,Marks,Attendance
1,Bharti,ISE,91,93
2,Shwetank,CSE,84,88
